### ISSUE TITLE
Refine Search

### ISSUE THREAD

**Issue by jsills3110** [jsills3110/Project-1#23]
### Task(s)
- [ ] Give the user the ability to search by recipe type
- [ ] Give the user the ability to search by ingredients
- [ ] Give the user the ability to get more search results
