### ISSUE TITLE
Create Users

### ISSUE THREAD

**Issue by jsills3110** [jsills3110/Project-1#38]
### Task(s)
- [ ] Create a log in page
- [x] Create users in the database
- [x] create sing up page
